export const country_data = [
{code: "AF", Name: "Afghanistan"},
{code: "AL", Name: "Albania"},
{code: "DZ", Name: "Algeria"},
{code: "AS", Name: "American Samoa"},
{code: "AD", Name: "Andorra"},
{code: "AO", Name: "Angola"},
{code: "AI", Name: "Anguilla"},
{code: "AQ", Name: "Antarctica"},
{code: "AG", Name: "Antigua and Barbuda"},
{code: "AR", Name: "Argentina"},
{code: "AM", Name: "Armenia"},
{code: "AW", Name: "Aruba"},
{code: "AU", Name: "Australia"},
{code: "AT", Name: "Austria"},
{code: "AZ", Name: "Azerbaijan"},
{code: "BS", Name: "Bahamas"},
{code: "BH", Name: "Bahrain"},
{code: "BD", Name: "Bangladesh"},
{code: "BB", Name: "Barbados"},
{code: "BY", Name: "Belarus"},
{code: "BE", Name: "Belgium"},
{code: "BZ", Name: "Belize"},
{code: "BJ", Name: "Benin"},
{code: "BM", Name: "Bermuda"},
{code: "BT", Name: "Bhutan"},
{code: "BO", Name: "Bolivia, Plurinational State of"},
{code: "BQ", Name: "Bonaire, Sint Eustatius and Saba"},
{code: "BA", Name: "Bosnia and Herzegovina"},
{code: "BW", Name: "Botswana"},
{code: "BV", Name: "Bouvet Island"},
{code: "BR", Name: "Brazil"},
{code: "IO", Name: "British Indian Ocean Territory"},
{code: "BN", Name: "Brunei Darussalam"},
{code: "BG", Name: "Bulgaria"},
{code: "BF", Name: "Burkina Faso"},
{code: "BI", Name: "Burundi"},
{code: "KH", Name: "Cambodia"},
{code: "CM", Name: "Cameroon"},
{code: "CA", Name: "Canada"},
{code: "CV", Name: "Cape Verde"},
{code: "KY", Name: "Cayman Islands"},
{code: "CF", Name: "Central African Republic"},
{code: "TD", Name: "Chad"},
{code: "CL", Name: "Chile"},
{code: "CN", Name: "China"},
{code: "CX", Name: "Christmas Island"},
{code: "CC", Name: "Cocos (Keeling) Islands"},
{code: "CO", Name: "Colombia"},
{code: "KM", Name: "Comoros"},
{code: "CG", Name: "Congo"},
{code: "CD", Name: "Congo, the Democratic Republic of the"},
{code: "CK", Name: "Cook Islands"},
{code: "CR", Name: "Costa Rica"},
{code: "CI", Name: "Cte d'Ivoire"},
{code: "HR", Name: "Croatia"},
{code: "CU", Name: "Cuba"},
{code: "CW", Name: "Curaao"},
{code: "CY", Name: "Cyprus"},
{code: "CZ", Name: "Czech Republic"},
{code: "DK", Name: "Denmark"},
{code: "DJ", Name: "Djibouti"},
{code: "DM", Name: "Dominica"},
{code: "DO", Name: "Dominican Republic"},
{code: "EC", Name: "Ecuador"},
{code: "EG", Name: "Egypt"},
{code: "SV", Name: "El Salvador"},
{code: "GQ", Name: "Equatorial Guinea"},
{code: "ER", Name: "Eritrea"},
{code: "EE", Name: "Estonia"},
{code: "ET", Name: "Ethiopia"},
{code: "FK", Name: "Falkland Islands (Malvinas)"},
{code: "FO", Name: "Faroe Islands"},
{code: "FJ", Name: "Fiji"},
{code: "FI", Name: "Finland"},
{code: "FR", Name: "France"},
{code: "GF", Name: "French Guiana"},
{code: "PF", Name: "French Polynesia"},
{code: "TF", Name: "French Southern Territories"},
{code: "GA", Name: "Gabon"},
{code: "GM", Name: "Gambia"},
{code: "GE", Name: "Georgia"},
{code: "DE", Name: "Germany"},
{code: "GH", Name: "Ghana"},
{code: "GI", Name: "Gibraltar"},
{code: "GR", Name: "Greece"},
{code: "GL", Name: "Greenland"}
,{code: "GD", Name: "Grenada"},
{code: "GP", Name: "Guadeloupe"},
{code: "GU", Name: "Guam"},
{code: "GT", Name: "Guatemala"},
{code: "GG", Name: "Guernsey"},
{code: "GN", Name: "Guinea"},
{code: "GW", Name: "Guinea-Bissau"},
{code: "GY", Name: "Guyana"},
{code: "HT", Name: "Haiti"},
{code: "HM", Name: "Heard Island and McDonald Islands"},
{code: "VA", Name: "Holy See (Vatican City State)"},
{code: "HN", Name: "Honduras"},
{code: "HK", Name: "Hong Kong"}
,{code: "HU", Name: "Hungary"},
{code: "IS", Name: "Iceland"},
{code: "IN", Name: "India"},
{code: "ID", Name: "Indonesia"},
{code: "IR", Name: "Iran, Islamic Republic of"},
{code: "IQ", Name: "Iraq"},
{code: "IE", Name: "Ireland"},
{code: "IM", Name: "Isle of Man"},
{code: "IL", Name: "Israel"},
{code: "IT", Name: "Italy"},
{code: "JM", Name: "Jamaica"},
{code: "JP", Name: "Japan"},
{code: "JE", Name: "Jersey"}
,{code: "JO", Name: "Jordan"},
{code: "KZ", Name: "Kazakhstan"},
{code: "KE", Name: "Kenya"},
{code: "KI", Name: "Kiribati"},
{code: "KP", Name: "Korea, Democratic People's Republic of"},
{code: "KR", Name: "Korea, Republic of"},
{code: "KW", Name: "Kuwait"},
{code: "KG", Name: "Kyrgyzstan"},
{code: "LA", Name: "Lao People's Democratic Republic"},
{code: "LV", Name: "Latvia"},{code: "LB", Name: "Lebanon"},{code: "LS", Name: "Lesotho"},
{code: "LR", Name: "Liberia"},
{code: "LY", Name: "Libya"},
{code: "LI", Name: "Liechtenstein"},
{code: "LT", Name: "Lithuania"},
{code: "LU", Name: "Luxembourg"},
{code: "MO", Name: "Macao"},
{code: "MK", Name: "Macedonia, the Former Yugoslav Republic of"},
{code: "MG", Name: "Madagascar"},
{code: "MW", Name: "Malawi"},
{code: "MY", Name: "Malaysia"},
{code: "MV", Name: "Maldives"},
{code: "ML", Name: "Mali"},
{code: "MT", Name: "Malta"},
{code: "MH", Name: "Marshall Islands"},
{code: "MQ", Name: "Martinique"},
{code: "MR", Name: "Mauritania"},
{code: "MU", Name: "Mauritius"},
{code: "YT", Name: "Mayotte"},
{code: "MX", Name: "Mexico"},
{code: "FM", Name: "Micronesia, Federated States of"},
{code: "MD", Name: "Moldova, Republic of"},
{code: "MC", Name: "Monaco"},
{code: "MN", Name: "Mongolia"},
{code: "ME", Name: "Montenegro"},
{code: "MS", Name: "Montserrat"},
{code: "MA", Name: "Morocco"},
{code: "MZ", Name: "Mozambique"},
{code: "MM", Name: "Myanmar"},
{code: "NA", Name: "Namibia"},
{code: "NR", Name: "Nauru"},
{code: "NP", Name: "Nepal"},
{code: "NL", Name: "Netherlands"},
{code: "NC", Name: "New Caledonia"},
{code: "NZ", Name: "New Zealand"},
{code: "NI", Name: "Nicaragua"},
{code: "NE", Name: "Niger"},
{code: "NG", Name: "Nigeria"},
{code: "NU", Name: "Niue"},
{code: "NF", Name: "Norfolk Island"},
{code: "MP", Name: "Northern Mariana Islands"},
{code: "NO", Name: "Norway"},
{code: "OM", Name: "Oman"},
{code: "PK", Name: "Pakistan"},
{code: "PW", Name: "Palau"}
,{code: "PS", Name: "Palestine, State of"},
{code: "PA", Name: "Panama"},
{code: "PG", Name: "Papua New Guinea"},
{code: "PY", Name: "Paraguay"},
{code: "PE", Name: "Peru"},
{code: "PH", Name: "Philippines"},
{code: "PN", Name: "Pitcairn"},
{code: "PL", Name: "Poland"},
{code: "PT", Name: "Portugal"},
{code: "PR", Name: "Puerto Rico"},
{code: "QA", Name: "Qatar"},
{code: "RE", Name: "Runion"},
{code: "RO", Name: "Romania"},
{code: "RU", Name: "Russian Federation"},
{code: "RW", Name: "Rwanda"},
{code: "BL", Name: "Saint Barthlemy"},
{code: "SH", Name: "Saint Helena, Ascension and Tristan da Cunha"},
{code: "KN", Name: "Saint Kitts and Nevis"},
{code: "LC", Name: "Saint Lucia"},
{code: "MF", Name: "Saint Martin (French part)"},
{code: "PM", Name: "Saint Pierre and Miquelon"},
{code: "VC", Name: "Saint Vincent and the Grenadines"},
{code: "WS", Name: "Samoa"},
{code: "SM", Name: "San Marino"},
{code: "ST", Name: "Sao Tome and Principe"}
,{code: "SA", Name: "Saudi Arabia"},
{code: "SN", Name: "Senegal"},{
    code: "RS", Name: "Serbia"},
{code: "SC", Name: "Seychelles"},
{code: "SL", Name: "Sierra Leone"},
{code: "SG", Name: "Singapore"},
{code: "SX", Name: "Sint Maarten (Dutch part)"},
{code: "SK", Name: "Slovakia"},
{code: "SI", Name: "Slovenia"},
{code: "SB", Name: "Solomon Islands"},
{code: "SO", Name: "Somalia"},
{code: "ZA", Name: "South Africa"},
{code: "GS", Name: "South Georgia and the South Sandwich Islands"},
{code: "SS", Name: "South Sudan"},
{code: "ES", Name: "Spain"},
{code: "LK", Name: "Sri Lanka"},
{code: "SD", Name: "Sudan"},
{code: "SR", Name: "Suriname"},
{code: "SJ", Name: "Svalbard and Jan Mayen"},
{code: "SZ", Name: "Swaziland"},
{code: "SE", Name: "Sweden"},
{code: "CH", Name: "Switzerland"},
{code: "SY", Name: "Syrian Arab Republic"},
{code: "TW", Name: "Taiwan, Province of China"},
{code: "TJ", Name: "Tajikistan"},
{code: "TZ", Name: "Tanzania, United Republic of"},
{code: "TH", Name: "Thailand"}
,{code: "TL", Name: "Timor-Leste"},
{code: "TG", Name: "Togo"},
{code: "TK", Name: "Tokelau"},
{code: "TO", Name: "Tonga"}
,{code: "TT", Name: "Trinidad and Tobago"},
{code: "TN", Name: "Tunisia"},
{code: "TR", Name: "Turkey"},
{code: "TM", Name: "Turkmenistan"},
{code: "TC", Name: "Turks and Caicos Islands"},

{code: "TV", Name: "Tuvalu"},
{code: "UG", Name: "Uganda"},
    {code: "UA", Name: "Ukraine"},
    {code: "AE", Name: "United Arab Emirates"},
    {code: "GB", Name: "United Kingdom"},
    {code: "US", Name: "United States"},
    {code: "UM", Name: "United States Minor Outlying Islands"},
    {code: "UY", Name: "Uruguay"},
    {code: "UZ", Name: "Uzbekistan"},
    {code: "VU", Name: "Vanuatu"}
    ,{code: "VE", Name: "Venezuela, Bolivarian Republic of"}
    ,{code: "VN", Name: "Viet Nam"},
    {code: "VG", Name: "Virgin Islands, British"},
    {code: "VI", Name: "Virgin Islands, U.S."},
    {code: "WF", Name: "Wallis and Futuna"},
    {code: "EH", Name: "Western Sahara"},
    {code: "YE", Name: "Yemen"},
    {code: "ZM", Name: "Zambia"},
    {code: "ZW", Name: "Zimbabwe"}]
